// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pendlerapp.Data;

#nullable disable

namespace Pendlerapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505103710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Pendlerapp.Models.Favoritt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrukerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FraStoppested")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FraStoppestedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Opprettet")
                        .HasColumnType("TEXT");

                    b.Property<string>("TilStoppested")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TilStoppestedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Favoritter");
                });

            modelBuilder.Entity("Pendlerapp.Models.Reisehistorikk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Brukt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FaktiskAvgangstid")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavorittId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FavorittId");

                    b.ToTable("Reisehistorikker");
                });

            modelBuilder.Entity("Pendlerapp.Models.Reisehistorikk", b =>
                {
                    b.HasOne("Pendlerapp.Models.Favoritt", "Favoritt")
                        .WithMany("Reisehistorikker")
                        .HasForeignKey("FavorittId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favoritt");
                });

            modelBuilder.Entity("Pendlerapp.Models.Favoritt", b =>
                {
                    b.Navigation("Reisehistorikker");
                });
#pragma warning restore 612, 618
        }
    }
}
